# Generated by Django 5.2.5 on 2025-08-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoFormModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearFormChoice', models.CharField(choices=[('flyer-coffee', 'Flyer at a coffee shop'), ('flyer-library', 'Flyer at a Library'), ('word_of_mouth', 'Word of mouth'), ('friend', 'Through a friend')], max_length=30)),
                ('name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
