# Generated by Django 5.2.5 on 2025-08-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfoformmodal',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
